Docs and example for Error handling/exceptions vs error codes
AndcultureCode/AndcultureCode pull request #100
Opened 2021-05-17 12:03 UTC by dylanjustice

#97 Documentation for the first section of Clean Code / Exceptions
- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [/] Code builds cleanly (no _additional_ warnings or errors)
- [/] Manually tested
- [/] Automated tests are passing
- [/] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [/] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

2021-05-17 13:27 UTC, jstevenson approved these changes

2021-05-17 14:06 UTC, dylanjustice commented on clean-code/ERROR-HANDLING.md
> +    private DeviceHandle GetHandle(DeviceId id) {
Good catch!

2021-05-19 23:14 UTC, brandongregoryscott requested changes

2021-05-19 23:14 UTC, brandongregoryscott commented on clean-code/ERROR-HANDLING.md
> +In practice, we tend to follow stricter policy regarding when an `Exception` should be used. In the normal flow of a program, we prefer to bubble up errors through the `IResult<T>` pattern and only t
Thought: since we are attempting to tailor this documentation to be applicable to our own patterns, I question the value of the current code snippet. I would prefer this description to be right before the code snippet, and the code snippet rewritten in a way that shows the way we handle errors with `IResult`

2021-05-24 11:54 UTC, wintondeshong approved these changes
Thanks for putting this together @dylanjustice - approving assuming typo and minor phrasing will be reviewed

2021-05-24 11:54 UTC, wintondeshong commented on clean-code/ERROR-HANDLING.md
> +# Clean Code: Formatting
Nitpick: Copy paste error - Should be 'Error Handling' to match the chapter

2021-05-24 11:54 UTC, wintondeshong commented on clean-code/ERROR-HANDLING.md
> +Error codes are a relic of languages that didn't have exceptions. Since we work with languages that do support exceptions, we do not use error codes in our applications. Code that uses error codes ca
Suggestion: Consider "softening" the proclamation that it is a 'relic' of languages that didn't have exceptions. While clean code is a great book and much of its principles hold true. We should remember it isn't new. Believe it was published in 2008 or something like that. The pendulum is very much swinging the other direction with languages like Golang and Rust that purposely are excluding exceptions in favor of using error objects for normal flow control.

2021-05-24 12:33 UTC, dylanjustice commented
@brandongregoryscott @wintondeshong @jstevenson Refactored the code snippet per BScott's comments. Assuming there will be some additional commentary to go along with that 😂 Have at it!

2021-05-25 18:27 UTC, brandongregoryscott commented on clean-code/ERROR-HANDLING.md
> +        r.AddError(key: ERROR_KEY_DEVICE_SHUTDOWN_FAILURE, message: ex.Message);
Throwing and recatching a specific exception here seems like an anti-pattern - more work/code to do the same thing as `r.AddError(ERROR_KEY_DEVICE_SHUTDOWN_FAILURE, message)`. Honestly, I struggle to find appropriate scenarios to throw exceptions vs. just using our standard errors. Maybe a more appropriate area would be at the top of `ShutDown`?

```cs
if (string.IsNullOrWhiteSpace(DEV1))
{
    throw new ArgumentNullException("Device handle was unexpectedly null or empty.");
}
```

2021-05-26 12:41 UTC, dylanjustice commented on clean-code/ERROR-HANDLING.md
> +        r.AddError(key: ERROR_KEY_DEVICE_SHUTDOWN_FAILURE, message: ex.Message);
That's fine. I was more trying to adapt the snippet from the book to highlight the point. Happy to change it.

2021-05-26 19:40 UTC, brandongregoryscott approved these changes

2021-05-26 19:43 UTC, brandongregoryscott commented
Thanks for taking into consideration all the feedback!

2021-05-26 22:15 UTC, merged