added data structure object anti-symmetry documentation
AndcultureCode/AndcultureCode pull request #94
Opened 2021-04-11 16:49 UTC by joshuapeters

#80 Added documentation surrounding our use of Data Structures and Objects, and how they relate to their nature asymmetry of each other.

2021-04-12 11:25 UTC, jstevenson approved these changes

2021-04-12 11:25 UTC, jstevenson commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +## Objects and Data Structures
This seems like a redundant, extra level of hierarchy. I believe this should be removed, and `### Data Structure/Object Anti-Symmetry` changed to `## Data Structure/Object Anti-Symmetry`.

2021-04-13 13:40 UTC, joshuapeters commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +## Objects and Data Structures
Updated!

2021-04-19 20:23 UTC, brandongregoryscott requested changes
Some typos & redundancy to clean up and I'm good to approve 👍

2021-04-19 20:23 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +A Data Structure shares it's data pubicly, and has no functions inherent to the data structure to act upon that data.
Should be `its` (possessive) instead of `it's` (it is). Something about the wording here is strange, too - "has no functions inherent to the data structure to act upon that data" - could this be reduced to "has no functions to act upon the underlying data"?

2021-04-19 20:23 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +    public string Email     { get; set; }
Nitpick: In an effort to keep our code samples consistent, I would alphabetize these (and probably not align them - I think we've concluded that horizontal alignment is probably not worth the effort according to the FORMATTING.md doc)

2021-04-19 20:23 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +    LastName:  string;
Same here - in TS, we typically do not uppercase property/function names

2021-04-19 20:23 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +An example of how we'd often use Objects can be seen in our use of Immutable, and our Record pattern ont he front end.
Typo: `on the` (though this seems to be restating the last sentence)

2021-04-19 20:23 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +In our projects we often take more functional approaches to business logic implementation. However, an example of the asymmetry of Objects to Data Structures can be viewed in the way we often use Imm
The second 'often' in this sentence could be taken out

2021-05-25 18:08 UTC, wintondeshong commented
@joshuapeters think you can check this feedback out by the next meeting in 2 weeks?

2021-06-08 18:39 UTC, brandongregoryscott approved these changes
Aside from the small alignment thing, looks good! Thanks for taking care of that feedback

2021-06-08 18:39 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +    email:     string;
Looks like this block was missed in the last commit to revert the alignment 👍

2021-07-06 16:25 UTC, merged