Clean Code: Objects and Data Structures: The Law of Demeter
AndcultureCode/AndcultureCode pull request #95
Opened 2021-04-12 13:16 UTC by jstevenson

Clean Code: Objects and Data Structures: The Law of Demeter - https://github.com/AndcultureCode/AndcultureCode/issues/81

[x] Related GitHub issue(s) linked in PR description
[x] Destination branch merged, built and tested with your changes
[x] Code formatted and follows best practices and patterns
- [ ] Code builds cleanly (no _additional_ warnings or errors)
- [ ] Manually tested
- [ ] Automated tests are passing
- [ ] No _decreases_ in automated test coverage
- [ ] Documentation updated (readme, docs, comments, etc.)
- [ ] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

2021-04-19 20:55 UTC, brandongregoryscott requested changes
Left some thoughts/typos for consideration. Would love to hear others' thoughts too!

2021-04-19 20:55 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +var outputStream = ctxt.createScratchFileStream(classFileName);
Instead of copying the variable names verbatim from the book, consider renaming or rewriting the example with contrived names that would better fit our naming standards

2021-04-19 20:55 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +var outputDirectory = scratchDirectory.getAbsolultePath();
Typo: `Absolute`

2021-04-19 20:55 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +var outputDirectory = ctxt.options.scratchDirectory.absolultePath;
Typo: `Absolute`

2021-04-19 20:55 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +But whether this defies the Law of Demeter or not depends if the classes for `ctxt`, `options`
Part of me wonders if this paragraph is necessary - especially with the language features of C# (automatic property accessors & the ability to have custom get/set functions), the line is much more blurred and `ctxt.options.scratchDirectory.absolultePath;` might still be _technically_ violating the rule. I think the most important takeaway is below - creating methods that hide the underlying structure to avoid track wrecks.

2021-04-20 13:33 UTC, jstevenson commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +But whether this defies the Law of Demeter or not depends if the classes for `ctxt`, `options`
@brandongregoryscott  The other fixes are in place, but yeah, I am not sure about this either. I could change it to the following, or just drop it completely:

```But whether this defies the Law of Demeter or not depends if the classes for context, options and scratchDirectory are data structures or objects. C# muddies the water with the ability to have advanced functionality within get/set object accessors. If you know that all of the classes are DTOs, then the following structure could be used (though it isn't ideal):

var outputDirectory = context.Options.ScratchDirectory.AbsolutePath;```

2021-04-20 18:26 UTC, brandongregoryscott commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +But whether this defies the Law of Demeter or not depends if the classes for `ctxt`, `options`
I like this explanation a lot more - relevant to &C's standard stack and still gets the point across to avoid diving if possible. Would like to hear others' feedback too 👍

2021-04-26 12:12 UTC, dylanjustice approved these changes

2021-04-26 12:42 UTC, dylanjustice commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +But whether this defies the Law of Demeter or not depends if the classes for `ctxt`, `options`
Agreed. Option 2!

2021-04-27 12:18 UTC, joshuapeters commented on clean-code/OBJECTS-AND-DATA-STRUCTURES.md
> +But whether this defies the Law of Demeter or not depends if the classes for `ctxt`, `options`
Agreed!

2021-04-27 12:18 UTC, joshuapeters approved these changes

2021-04-27 12:25 UTC, brandongregoryscott approved these changes

2021-04-27 12:34 UTC, merged